version: '3.9'
services:
    # Utils
    utils:
        container_name: utils
        build:
            context: .
            dockerfile: Dockerfile
        image: utils:1.0
        volumes:
          - .:/home/app
          - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev