name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint Fix
      run: npm run lint:fix
    - name: Run Jest Test
      run: npm run test
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests

